### ISSUE TITLE
Add instrumentation - tracing

### ISSUE THREAD

**Issue by deezone** [deezone/HydroBytes-BaseStation#63]
Following the instructions in:

**Ardan Labs** - **Ultimate Service Version 1**
**Getting Production Ready - Tracing requests**
https://education.ardanlabs.com/courses/take/ultimate-service-ver-1/lessons/7976150-19-1-tracing

Add tracing using Open Zipkin (https://zipkin.io/) as a sidecar:
```
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411
```
